{
  "extends": [
    "@keboola/node",
    "plugin:flowtype/recommended"
  ],
  "plugins": [
    "flowtype",
    "flowtype-errors",
    "import"
  ],
  "env": {
    "node": true,
    "mocha": true
  },
  "rules": {
    "import/no-cycle": 0,
    "flowtype-errors/show-errors": 2,
    "flowtype-errors/show-warnings": 1
  }
}
