language: node_js

node_js:
- node

script:
  - ./node_modules/.bin/mocha --timeout 0 --require babel-register --require source-map-support test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: keboola/storage-api-js-client
    branch: master
