language: node_js

node_js:
- node

before_script:
  - yarn lint

script:
  - yarn test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: keboola/storage-api-js-client
    branch: master
