language: node_js

node_js:
- node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install
  - yarn lint

script:
  - yarn test

deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: keboola/storage-api-js-client
    branch: master
