name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install && yarn list --installed
      - name: Lint code
        run: yarn lint
      - name: Typescript check
        run: yarn check-types
      - name: Run tests
        run: yarn test
        env:
          KBC_URL: https://connection.keboola.com
          KBC_TOKEN: ${{ secrets.KBC_TOKEN }}
          KBC_COMPONENT: keboola.ex-db-mysql
