name: "Publish"
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Publish
        run: npm publish --tag ${GITHUB_REF#"refs/tags/"}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
